services:
  - type: web
    name: news-digest-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
